name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        echo "Setting up Python environment"
        python -m venv venv
        . venv/bin/activate
        echo "Installing dependencies"
        pip install -r requirements.txt

    - name: Run simple echo command
      run: |
        echo "Running tests..."
        echo "All tests passed!"  # Simulating running tests

    - name: Final echo to confirm pipeline
      run: |
        echo "CI pipeline completed successfully!"
