# Generated by Django 5.1.4 on 2024-12-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_api_product_categor_5c53c5_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_categor_5c53c5_idx',
        ),
    ]
